name: On Release Workflow

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update 'version' file
        run: |
          export VERSION="${{ github.event.release.tag_name }}"
          sed -i "s/^version:.*$/version: ${VERSION}/" charts/temporal/Chart.yaml

      # Commit the updated 'version' file
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update version number'
          branch: master
          add: '["charts/temporal/Chart.yaml"]'

      # Publish the Helm chart
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          linting: 'off'
